### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no lbfgsb_wrapper in java.library.path ?

### ISSUE THREAD

**Issue by c0der1337** [mkobos/lbfgsb_wrapper#3]
Hello guys,

 I try to use lbfgsb_wrapper for my code. Therefore I added the lbfgsb_wrapper-1.1.2.jar to the build path and run the sample code. I got the following error message:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no lbfgsb_wrapper in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at lbfgsb.Wrapper.<clinit>(Wrapper.java:15)
	at lbfgsb.Minimizer.run(Minimizer.java:94)
	at LBFGSB_Test.main(LBFGSB_Test.java:22)

Do you have any idea why I got it and how to fix it? I m using windows and eclipse.

Thanks in advance

**Comment by mkobos** [comment]
Hi,

It seems that the program is not able to find the binary library. The sample `run1.sh` and `run2.sh` scripts show how to set the library path properly. 

However, the real problem is that library itself (the file with the `*.so` extension) has Linux format so you won't be able to use it on a Windows machine. This wrapper library was written with Linux/Unix in mind - I have no idea how to compile it for a Windows environment.

**Comment by bayanhmdn** [comment]
Hello,

Any updates on this? I am facing the same issue. Is there no way to run it on Windows?

**Comment by mkobos** [comment]
Unfortunately, I don't have any information about anybody running it on Windows and I haven't tried to do it myself.

**Comment by bayanhmdn** [comment]
Thanks for the reply! I actually tried it in Linux as well and was having the same problem.

**Comment by mkobos** [comment]
Hi. I just downloaded the current version of the code, compiled it (`ant`), and run the test (`ant test`) and it all succeed. Then, I run the example script `./bin/linux_run1.sh` that shows how to use the library and it also worked fine. I'm using Linux Ubuntu 18.04 system. Have you followed these steps as well?
